<a href="https://colab.research.google.com/github/Tinynja/Sarsa-phi-EB/blob/main/rl_paper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget -q https://raw.githubusercontent.com/Tinynja/AER8270-TD3/master/notebooks/ALE_Framework_Tests.ipynb

%run ALE_Framework_Tests.ipynb

Cloning into 'Sarsa-phi-EB'...
remote: Enumerating objects: 301, done.
remote: Counting objects: 100% (301/301), done.
remote: Compressing objects: 100% (250/250), done.
remote: Total 301 (delta 92), reused 204 (delta 39), pack-reused 0
Receiving objects: 100% (301/301), 740.97 KiB | 4.33 MiB/s, done.
Resolving deltas: 100% (92/92), done.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.3.post1 requires numpy<1.20,>=1.16.0, but you have numpy 1.21.4 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
arviz 0.11.4 requires typing-extensions<4,>=3.7.4.3, but you have typing-extensions 4.0.1 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
[SUPPORTED]                ms_pacman    ROMS/Ms. Pac-Man (1983).bin
[SUPPORT

/usr/local/lib/python3.7/dist-packages/ale_py/roms/utils.py:90: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for external in metadata.entry_points().get(self.group, []):


Skipped background regeneration.
Skipped displaying stored backgrounds to reduce ouptuts.
Skipped manual test.


sarsa phi eb

In [8]:
#######################################################################
# Copyright (C)                                                       #
# 2017-2018 Shangtong Zhang(zhangshangtong.cpp@gmail.com)             #
# Permission given to modify the code as long as you keep this        #
# declaration at the top                                              #
#######################################################################

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from math import floor
from tqdm import tqdm


# all possible actions
ACTIONS = range(4)

# discount is always 1.0 in these experiments
DISCOUNT = 0.99

# use optimistic initial value, so it's ok to set epsilon to 0
EPSILON = 0.01

# maximum steps per episode
STEP_LIMIT = 5000


# get action at @position and @velocity based on epsilon greedy policy and @valueFunction  #########################    use our own get_action. modified it, may work as intended
def get_action(observation, valueFunction):
    if np.random.binomial(1, EPSILON) == 1:
        return np.random.choice(ACTIONS)
    values = []
    for action in ACTIONS:
        values.append(valueFunction.value(observation))  
    return np.argmax(values)



# replacing trace update rule
# @trace: old trace (will be modified)
# @activeTiles: current active tile indices
# @lam: lambda
# @return: new trace for convenience
def replacing_trace(trace, activeTiles, lam):
    active = (torch.arange(len(trace)).to(device)[None,...] == activeTiles.flatten()[...,None]).any(0)
    trace[active] = 1
    trace[~active] *= lam * DISCOUNT
    return trace



# wrapper class for Sarsa(lambda)
class Sarsa:
    # In this example I use the tiling software instead of implementing standard tiling by myself
    # One important thing is that tiling is only a map from (state, action) to a series of indices
    # It doesn't matter whether the indices have meaning, only if this map satisfy some property
    # View the following webpage for more information
    # http://incompleteideas.net/sutton/tiles/tiles3.html
    # @maxSize: the maximum # of indices
    #the hashing is a lfa?
    def __init__(self, step_size, lam, trace_update=replacing_trace, max_size=28672):
        self.max_size = max_size
        self.trace_update = trace_update
        self.lam = lam

        # divide step size equally to each tiling
        self.step_size = step_size/10

        # weight for each tile
        self.weights =torch.zeros(max_size).to(device) #max size is the number of features?

        # trace for each tile
        self.trace = torch.zeros(max_size).to(device)



    # estimate the value of given state and action
    def value(self, observation):
        active_tiles = torch.nonzero(observation)
        return self.weights[active_tiles].sum()

    # learn with given state, action and target
    def learn(self, observation, target):
        active_tiles = torch.nonzero(observation)
        estimation = self.weights[active_tiles].sum()
        delta = target - estimation
        #print('estimation array: ' + str(self.weights[active_tiles]))
        print('estimation: ' + str(self.weights[active_tiles].sum()))
        if self.trace_update == replacing_trace:
            self.trace_update(self.trace, active_tiles, self.lam)
        else:
            raise Exception('Unexpected Trace Type')
        self.weights += self.step_size * delta * self.trace
        print('delta: ' + str(delta))
        print('weights: ' +  str(self.weights))


# play Mountain Car for one episode based on given method @evaluator
# @return: total steps in this episode
def play(evaluator, env):

    action = random.choice(ACTIONS)
    steps = 0
    while True:
        next_observation, reward, done, info = env.step(action)
        next_action = get_action(next_observation, evaluator)    #########################    use our own get_action  ??? modified it, may work as intented
        steps += 1
        target = reward + DISCOUNT * evaluator.value(next_observation)          ############# use our own value function ??? modified it, may work as intented
        evaluator.learn(observation, target)
        observation = next_observation
        action = next_action
        if done:
            break
        if steps >= STEP_LIMIT:
            print('Step Limit Exceeded!')
            break
    return steps

In [11]:
class BaseAgent:
  """ The base agent class function.
  """
  def __init__(self, nb_features=28672):
    #nothing for now
    self.gamma = 1
    self.features = nb_features
    self.rhos = torch.ones(self.features).to(device) #stores the rho_i values


  def takeAction(self, t):
    phis = [[0,1,0],[0,1,0],[0,1,0],[1,0,1]]
    return phis[t]


  def updateRho_i(self, counts, t):
    M = self.features
    self.rhos = (counts+1.5)/(t+1)
    return 0


  def PHI_EB(self, evaluator, env, beta=0.05, t_end=200):
    t = 0
    M = self.features #number of features
    counts = torch.zeros(M).to(device)
    states = torch.zeros(t_end,M).to(device) #stores the previous phis for all timesteps

    action = 1 #starting the game for the agent on the first game
    old_phi = env._observe()
    print('starting iterations')
    print('rhos: ' + str(self.rhos))
    while t < t_end:
      #observe phi(s), reward
      phi, reward, done, info = env.step(action)
      print('--------------------------------------------------------------')
      print('took action: ', env.action_space[action])
      next_action = get_action(phi, evaluator)
      print('phi: ' + str(phi))
      
      #compute rho_t(phi) (feature visit-density)
      if t > 0:
        counts = (phi==states[0:t]).sum(0)
        print(counts)
        self.rhos = (counts+0.5)/(t+1)
        print('rhos: ' + str(self.rhos))
        rho_t = torch.prod(self.rhos)
      else:
        rho_t = 0.5**M
      print('rho_t ' + str(rho_t))
      #update all rho_i with observed phi
      states[t] = phi
      self.updateRho_i(counts, t+1)
      print('min rho_i_t: ' + str(min(self.rhos)))
      
      #compute rho_t+1(phi)
      new_rho_t = 1
      for i in range(M):
        new_rho_t = new_rho_t*self.rhos[i]
      if new_rho_t <= 1e-323: #this is to avoid division by zero, might need to be tweaked
        new_rho_t = 1e-323
      print('new_rho_t ' + str(new_rho_t))

      #compute Nhat_t(s)
      Nhat_t = rho_t*(1-new_rho_t)/(new_rho_t-rho_t)
      if Nhat_t <= 1e-323: #this is to avoid division by zero again, might need to be tweaked
        Nhat_t = torch.tensor([1e-323]).to(device)

      #compute R(s,a) (empirical reward)
      explorationBonus = beta/torch.sqrt(Nhat_t)
      if torch.isnan(explorationBonus) or explorationBonus >= 1e15:
        explorationBonus = 1e15

      reward = reward + explorationBonus
      print('reward: ',reward)

      print('weights: ' + str(evaluator.weights))
      print('state value: ' + str(evaluator.value(phi)))
      #pass phi(s) and reward to RL algo to update theta_t
      target = reward + self.gamma * evaluator.value(phi)          ############# use our own value function ??? modified it, may work as intented
      evaluator.learn(old_phi, target)

      if done:
        #break
        env.reset()
        action = 1
        old_phi = env.observe()
        print('episode ended on step ', t, 'starting a new one')
      else:
        old_phi = phi
        action = next_action

      t += 1

    return evaluator.weights


In [13]:
from ale_py.roms import Breakout
env = EnvALE(Breakout, feature_type='Basic')
print(env.action_space)
alpha = 0.5
lam = 0.9
evaluator = Sarsa(alpha, lam, replacing_trace,28672)
agent = BaseAgent()
env.reset(do_record=False)
weights = agent.PHI_EB(evaluator, env, beta=0.05, t_end=2000)

[<Action.NOOP: 0>, <Action.FIRE: 1>, <Action.RIGHT: 3>, <Action.LEFT: 4>]
starting iterations
rhos: tensor([1., 1., 1.,  ..., 1., 1., 1.])
--------------------------------------------------------------
took action:  Action.FIRE
phi: tensor([ True, False, False,  ..., False, False, False])
rho_t 0.0
min rho_i_t: tensor(0.7500)
new_rho_t tensor(2.8026e-45)
reward:  1000000000000000.0
weights: tensor([0., 0., 0.,  ..., 0., 0., 0.])
state value: tensor(0.)
estimation: tensor(0.)
delta: tensor(1.0000e+15)
weights: tensor([2.5000e+12, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00])
--------------------------------------------------------------
took action:  Action.NOOP
phi: tensor([ True, False, False,  ..., False, False, False])
tensor([1, 1, 1,  ..., 1, 1, 1])
rhos: tensor([0.7500, 0.7500, 0.7500,  ..., 0.7500, 0.7500, 0.7500])
rho_t tensor(0.)
min rho_i_t: tensor(0.8333)
new_rho_t tensor(2.8026e-45)
reward:  1000000000000000.0
weights: tensor([2.5000e+12, 0.0000

In [ ]:
#optimisation tests
%%timeit
t = 1
M = 28000
counts = np.zeros(M)
rhos = np.ones(M)
for i in range(M): #M is the number of features of phi
  counts[i] += 1 #since we add phi to the seen states, all the counts are increased by one for t+1
  rhos[i] = (counts[i]+0.5)/(t+1)

10 loops, best of 5: 36.7 ms per loop


In [ ]:
#best one
%%timeit
t = 1
M = 28000
counts = np.zeros(M)
rhos = np.ones(M)
rhos = (counts+1.5)/(t+1)

The slowest run took 12.92 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 54.5 µs per loop


In [ ]:
#compute rho_t(phi) (feature visit-density)
%%timeit
t = 0
t_end = 30
M = 10000
phis = np.zeros((t_end,M))
counts = np.zeros(M)
states = np.zeros((t_end,M))
rhos = np.ones(M)
while t < t_end:
  phi = phis[t]
  if t > 0:
    rho_t = 1
    for i in range(M):
      counts[i] = 0
      for step in range(t):
        if phi[i] == states[step,i]:
          counts[i] += 1
      rhos[i] = (counts[i]+0.5)/(t+1)
      rho_t = rho_t*rhos[i]
  else:
    rho_t = 0.5**M

  #updating rho (other method)
  states[t] = phi
  counts += 1
  rhos = (counts+0.5)/(t+2)
  
  t += 1

1 loop, best of 5: 4.51 s per loop


In [ ]:
#compute rho_t(phi) (feature visit-density)
%%timeit
t = 0
t_end = 5000
M = 1000
phis = np.zeros((t_end,M))
counts = np.zeros(M)
states = np.zeros((t_end,M))
rhos = np.ones(M)
while t < t_end:
  phi = phis[t]
  if t > 0:
    rho_t = 1
    counts = np.zeros(M)
    for step in range(t):
      counts[np.where(phi == states[step])] += 1
    rhos = (counts+0.5)/(t+1)
    rho_t = np.prod(rhos)
  else:
    rho_t = 0.5**M

  #updating rho (other method)
  states[t] = phi
  counts += 1
  rhos = (counts+0.5)/(t+2)
  
  t += 1

1 loop, best of 5: 2min 19s per loop


In [ ]:
#version 3 of optimisation
%%timeit
t = 0
t_end = 5000
M = 1000
#phis = [[0,1,0],[0,1,0],[0,1,0],[1,1,0]]
phis = np.zeros((t_end,M))
counts = np.zeros(M)
states = np.zeros((t_end,M))
rhos = np.ones(M)
while t < t_end:
  phi = phis[t]
  if t > 0:
    rho_t = 1
    counts = np.sum(np.where(phi == states[0:t],1,0),axis=0)
    rhos = (counts+0.5)/(t+1)
    rho_t = np.prod(rhos)
  else:
    rho_t = 0.5**M

  #updating rho (other method)
  states[t] = phi
  counts += 1
  rhos = (counts+0.5)/(t+2)
  
  t += 1

1 loop, best of 5: 45.1 s per loop


In [ ]:
print(phi)
print(states)
print(np.sum(np.where(phi == states,1,0),axis=0))
print(counts[phi == states[3]])

[1, 1, 0]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 1. 0.]]
[1 4 4]
[0. 0. 0.]
